version: "3.7"

services:
  web:
    build: .
    depends_on:
      - database
    ports:
      - "3000:3000"

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Mohit@4426
    ports:
      - "5432:5432"

  seed:
    build: .
    depends_on:
      - database
    command : sh -c "./node_modules/.bin/sequelize db:migrate"
    